-- phpMyAdmin SQL Dump
-- version 2.11.1
-- http://www.phpmyadmin.net
--
-- Host: thompson.safesecureweb.com
-- Generation Time: May 27, 2009 at 06:22 AM
-- Server version: 4.1.18
-- PHP Version: 5.1.6

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Database: `defacto2net`
--

-- --------------------------------------------------------

--
-- Table structure for table `magazinedetail`
--

CREATE TABLE IF NOT EXISTS `magazinedetail` (
  `magPrimName` varchar(255) NOT NULL default '',
  `magPrimBy` varchar(255) default NULL,
  `magPrimDir` varchar(255) default NULL,
  `magPrimDes` longtext,
  `magPrimText` tinyint(1) NOT NULL default '0',
  `magPrimScreen` varchar(255) default NULL,
  `dateAdded` datetime default NULL,
  `dateRevised` datetime default NULL,
  PRIMARY KEY  (`magPrimName`),
  KEY `Index_2` USING BTREE (`dateAdded`,`dateRevised`,`magPrimText`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `magazinedetail`
--

INSERT INTO `magazinedetail` (`magPrimName`, `magPrimBy`, `magPrimDir`, `magPrimDes`, `magPrimText`, `magPrimScreen`, `dateAdded`, `dateRevised`) VALUES
('3rd World Paki Report', 'Mind Bender &amp; The Shadow Master', '3rd.World.Paki.Report', 'Mind Bender and Shadow Master''s report on gaming group activity.', -1, NULL, NULL, NULL),
('Adrenalin', NULL, 'Adrenalin', 'Adrenalin is a very typical early nineties warez-magazine. This is not really a bad thing it is just simply there is nothing new or original here. The interface is your bog standard ANSI themed pull-down menu system. While the topics covered are the usual group politics, area code reports, interviews, game reviews and the like. Where Adrenalin does stand out though is it''s extensive content. It would definately take a while to read through every article in this magazine.', 0, 'adren-1', NULL, NULL),
('Advanced Pirate Technology', NULL, 'Advanced.Pirate.Technology', 'APT was the forerunner to what is considered the modern warez-magazine. It contained numerous articles that covered the underground as a whole with a focus on the cracking scene. The magazine had five dedicated sections which included VGA n'' ANSI, general articles, game reviews, submitted articles and news &amp; rumours.', 0, 'apt-mag3', NULL, NULL),
('Affinity', 'Canadian Born Coders', 'Affinity.Electronic.Magazine', 'Affinity was founded in 1996 to give the premier magazine of the time, Reality Check Network some competition. Unfortunately Affinity focused it''s efforts on it''s presentation over content. So while in the later issues the coding, music and art are extremely impressive, when compared to the competition it''s content is below par.', 0, 'aft-15', NULL, NULL),
('American Pirate Industries Newsletter', NULL, 'American.Pirate.Industries', 'This is a small but interesting newsletter for the group American Pirate Industries released back in 1989 during the early days of the IBM PC pirate scene.', -1, NULL, NULL, NULL),
('Anemia', NULL, 'Anemia', 'Anemia was a magazine that was heavily influenced by the likes of Reality Check Network, but it never quite made it in the quality stakes. Bad organisation or a lack of contacts meant that most of the articles written were never that interesting to read. Thankfully though in later issues this problem was solved.', 0, 'anemia4', NULL, NULL),
('Anti Warez Association', NULL, 'Anti.Warez.Association', 'These guys did the scene thing, got burned and wanted some payback. So Anti Warez Association was created in a bid to enlighten the misguided souls who remained active in the bad thing known as the warez scene. If these boys couldn''t join in the action anymore they sure as hell were going to at the very least get back at all those who cut them down.\r\n<p></p>\r\nSo what you end up with here is three issues of very humorous articles that make fun of the stereotypical ''warez kid''. Fortunately like all stereotypes they are not true for every one, unfortunately I bet you do know at least someone who could be described perfectly in one of these issues.', -1, 'awa', NULL, NULL),
('Brotherhood of Warez', NULL, 'Brother.Hood.Of.Warez', 'According to the Computer Underground Digest Archives this magazine started out as ''anti Big Brother association'', which was a HAPV report. The Brotherhood though is attempt at a not so serious magazine with a theme that parodies the bad parts of the kiddie warez scene. While this makes it humourous to browse through it also makes it a pain to read. One can almost say they went a bit too far, but maybe that was the point? Article wise they cover a variety of interests including all the stuff you would expect.', -1, 'bow', NULL, NULL),
('Classic Old Warez', NULL, 'Classic.Old.Warez', 'This was a one off magazine for the Efnet IRC channel #oldwarez. It mainly containing reviews of old games and the occasional interview.', -1, 'cow', NULL, NULL),
('Corruption', 'ACiD', 'Corruption', 'Corruption was originally a ANSI magazine that was founded by some active ACID members. The magazine was intended to be released every second month and survived for four issues. Unlike most magazines Corruption focused on all underground scenes including ANSI, HPAV, aswell as cracking.', 0, 'cor1', NULL, NULL),
('Courier Weektop Scorecard', NULL, 'cws', 'This surely has to be the longest running scene publication of all time. Coming in at 180 issues and generally released on a weekly basis, the CWS became a required read for all the courier kiddies out there.    <p></p>\r\nIt is unfortunate though, that for everyone else at the time. No one could give a damn. Though while it was courier chart magazine through and through, they did in various issues include scene news reports, interviews and on occasion team up with other publications. Infact from issue 80 onwards they included a copy of the scene game review publication Orgasming in every issue.', -1, 'cws', '2006-08-03 19:39:52', NULL),
('Cracking 101', 'Buckaroo Banzai of Neua', 'Cracking.101', 'A four part tutorial that goes into the how and what of cracking software for the IBM PC in the late eighties and early nineties. While this tutorial is completely irrelevant today seeing DOS and it''s software is long since dead. It does make an interesting read for those who have an interest in ancient computer technology.', -1, NULL, NULL, NULL),
('Cybermail', NULL, 'Cybermail', 'Cybermail started off with a lot of potential as a serious alternative independent scene magazine during late 1996. Unfortunately after the first issue the president and vice left and the magazine was taken over by it''s Australian based coder. He obviously didn''t have the same connections as the former leaders so in the later issues it lacks substance.', 0, 'cm-04', NULL, NULL),
('Defacto', NULL, 'Defacto', 'Defacto was founded in a bid to fill the gap left by Reality Check Network after their initial closing. While the magazine never gained the following that RCN commanded though it was generally considered an acceptable alternative.', 0, 'defacto8', NULL, NULL),
('Defacto2', NULL, 'Defacto2', 'An official sequal to the coded Defacto magazine created by the same people. Defacto2 was a monthly text based magazine that was eventually meant to evolve into a coded and HTML base. The magazine unfortunately only lasted three issues but most of these issues are packed to the brim with scene related articles and interviews.<p></p> This magazine eventually evolved into the Defacto2.net website that you see here and use today.', -1, 'df2', NULL, NULL),
('Dreadloc', NULL, 'Dreadloc', 'Dreadloc issue 1 is an interesting magazine. While the interface is ANSI based, it''s design is quite different, yet it works quite well. The magazine itself doesn''t contain much in the way of articles and of those most are mainly non-pirate related. \r\n<p></p>\r\nDreadloc ][ was released a year later and seems to use a newer interface. Unfortunately it does not work on any of our test machines.', 0, 'dlc-2', NULL, NULL),
('Fear Newsletter', 'Lucifer Enterprises', 'fear', 'Fear Newsletter seems to be a one off magazine released in early 1991 that was intended as a monthly series. Using a bizarrely programmed EGA text mode we found that the magazine hard problems working correctly in both DosBox and Windows Shell.\r\n\r\nInside you can find various scene game reviews, a small anarchy section and some BBS application reviews.', 0, 'fearcga1', '2007-07-14 00:59:37', '2007-08-01 06:16:52'),
('Future Scene News', NULL, 'Future.Scene.News', 'Future Scene News was founded on November 10th 1997 by BrainStew. Zerouser from Syndication was apparently the person in which inspired him to do so.<p></p><em>"It took us one long week to find a coder for the e-mag and we are thankful for that because now we gained two other coders because of him. Some people ask how we came up with the name Future Scene News, to be truthful, we had to find something to fit FSN because before this e-mag was created, I founded a quake clan called Fusion in which never really got around to doing so I changed it to my second best thing.  If you wonder how  we got the letters FSN out of Fusion then it''s the first, middle, and last letters in fusion."</em>', 0, 'fsn1', NULL, NULL),
('Galactic Review', NULL, 'Galactic.Game.Reviews', 'There is little known about this coded review magazine except for it was probably the first gaming review for the PC scene that was also coded. While the review used an unattractive  cheesy plasma VGA interface it also contained some indepth reviews and even some game screenshots.', 0, 'gala-08', NULL, NULL),
('Higher Mental Plane', NULL, 'Higher.Mental.Plane', 'Higher Mental Plane was created by Hooptie who was also the author of the Dreadloc series. Dreadloc ended abruptly when Hooptie was arrested along with a number of other people in his local 915 scene for issues related to arson. But less then two weeks later he was released and the charges were dropped. I guess after being released he decided to create a new magazine, and this is it.', 0, 'hmp_02', NULL, NULL),
('Hybrid Christmas Magazine', 'Hybrid', 'Hybrid.Xmas.96.Magazine', 'The magazine is something that one should not take too seriously as it was released just for some fun. It does though have some interesting articles and interviews plus a poll of the best groups of 1996. A sequel was meant to appear for the 1997 Christmas period but it never came to be.<p></p>For Windows 9x Only.', 0, 'hbd-xmas', NULL, NULL),
('Hype Magazine', NULL, 'Hype.Magazine', 'Hype Magazine has nothing really to do with articles but rather it is a show case of intros and loaders. Not only are the loaders displayed (with music) from within the magazine but information including titles, credits and phone numbers are given.', 0, 'hypemag2', NULL, NULL),
('Illuminatus', NULL, 'Illuminatus', 'Illuminatus is an interesting magazine from the 1991 period. It covered the pirate scene of the time, just not in very much detail. While the interface is quite bland and very DOS-like, the extensive range of articles makes it an enjoyable read. Just don''t expect anything to specific or detailed here.', 0, 'ill-5', NULL, NULL),
('Infinity', 'CIA', 'Infinity', 'Infinity was created by the art group CIA as a self promotional tool. Fortunately though there are enough interesting non-CIA articles to make it worth a read if you are not into the propaganda items.', 0, 'inf-03', NULL, NULL),
('Inquisition', NULL, 'Inquisition', 'Inquisition started out as a clone of The Week In Warez, just with a different name. Though over time Inquisition evolved, developing it''s own style away from it''s deflunked predecessor. Ironically Inquisition died the same way as The Week In Warez with simply no one bothering to continue work on it after issue eleven.<p></p>Inquisition was the last magazine (that was released on a regular basis) to be managed and edited by prominent scene members. This in turn gave Inquisition the unwanted reputation for being very bias towards some groups and even more bias against others.', -1, 'inq', NULL, NULL),
('Insanity', 'iCE', 'Insanity', 'Insanity is a coded magazine from 1991 period. It was started by the famous art group ICE and lasted for three issues before dying, quite an achievement for the time. This is a great magazine to read as it gives you a feeling of the old scene back when the art and pirate scenes were closely linked and a 486-25mhz (prequel to the original Intel Pentium) computer was considered damn fast.', 0, 'insan-1', NULL, NULL),
('Just The Facts', 'Class', 'Just.The.Facts', 'Not strictly an electronic magazine, this is more of what would be known as a chart-magazine. Released on a monthly basis Just The Facts kept track of all the ripped game releases, giving scores on their quality and quantity. These scores would be tallied showing who they thought were the best group of the month, and eventually the best of the year. The problem here though was that members of the prominent gaming group Class wrote it and so most people never trusted the scores.', 0, 'jtf9804', NULL, NULL),
('Lancelot', 'The Dream Team', 'lance1', 'Lancelot was a 1991 VGA based scene game review magazine released by The Dream Team and TRSi.\r\n<p></p>\r\nThe magazine was unique at the time being the first underground scene publication to use VGA graphics and Sound Blaster audio. It was the inspiration for a later unaffiliated magazine by ACID that was known as LanceLot2.', 0, 'lance-1', '2007-07-14 01:24:24', '2007-08-01 06:29:48'),
('Lancelot 2', 'ACiD/TDT', 'Lancelot2', 'Lancelot was originally a electronic magazine which was managed by The Dream Team and Tristar Red Sector Inc. back in 1991. But by December of that year it had been discontinued.\r\n<p></p>\r\nIn late 1992 an ACiD/The Dream Team member by the name of Sharp restarted the magazine, and hence the title Lancelot 2.\r\n<p class="italic">For some strange reason, Sharp wanted to pay homage to Hard Core with this magazine and so he named the magazine "Lancelot II" with his blessing. - RadMan (ACiD)</p>\r\nWhile the magazine itself focuses on the cracking scene of the period. It unfortunately lacks the number of interesting articles required to make it a great read.', 0, 'lance2-10', NULL, NULL),
('Mind Bender Warez Report aka The Warez Loop', NULL, 'MindBender.Warez.Report.1996', 'Summary of the gaming scene activities for 1996.', -1, NULL, NULL, NULL),
('PC ISO Game Charts', 'ISO News', 'PC.ISO.Game.Charts', 'Started by the ISO News website.', -1, NULL, NULL, NULL),
('Pirate', NULL, 'Pirate', 'Pirate is an early text magazine that primarily focused on the IBM PC. It is easy to see they where highly influenced by the hacking magazines of the time and veer too far in their own direction. This is proven by the fact that there are more articles on hacking and viruses in some issues then pirating. Also one might note that many of the articles are not original but reprinted items from previously release text files and mainstream news reports.', -1, NULL, NULL, NULL),
('Pirates Analyze Warez', NULL, NULL, 'PAW is a game review magazine from 1993 that covers floppy disk scene and consoles (mainly the Nintendo Super Entertainment System). The interface while being in VGA is not the easiest thing to use nor the most attractive to look at. But there are plenty of indepth reviews and every game gets it''s own score.', 0, NULL, NULL, NULL),
('Pirates Cove', 'Phrack Inc', 'Pirates.Cove', 'Phrack was a hacking publication that had been active for over two decades.\r\nDuring 1992 though they also included a section entitled ''Pirates Cove'' written by Rambone that as you can guess, covered the pirate scene.\r\nThe section itself was never too spectacular mainly containing small briefs and reprints of existing articles and text files.\r\n<p></p>\r\nThe complete collection of <a href="http://www.phrack.org">Phrack Magazine</a> is still online.', -1, 'phrack', NULL, NULL),
('Reality Check Network', 'Legacy', 'Reality.Check.Network', 'Reality Check Network started it''s roots as a promotional magazine for a game group called Legacy. Many people may disagree with me but if you go through the early issues you can see many reports that focused around this group, whether it is press releases or simply attacks against other competing groups. The first thirteen issues of Reality Check Network shows their innocence when they actually reported the news instead of creating it. These issues are worth looking back on just to see what started it all off. The issues contain a few good reports and interviews with people some who would eventually become leaders in the scene.\r\n<p></p>\r\nBy the time RCN died after issue 13 it had already built up a massive following within the mainstream scene, as well as with the members and leaders of the established scene groups. But when RCN returned in May 1996 they decided that being the biggest and the best wasn''t enough, they wanted more. So they did everything in their power to increase their readership, through advertising and other means. Though unfortunately this activity was fround upon by a selective and secretive underground scene that was essentially involved in illegal activities. And when there wasn''t enough news to complete an issue then these guys at Reality would simply stir the pot, so to speak to create something to report on.\r\n<p></p>\r\nEven though Reality Check Network managed to create it''s hard core haters of the magazine, it still managed to gain critical support from all the main groups from around the world. Well for a while at least.', 0, 'rcn-15', NULL, NULL),
('Relativity', NULL, 'Relativity', 'Relativity is a magazine that on the surface looks very similar to the old Reality Check Network issues. Heck they even use the same background music. Relativity differs though as it tries to be a magazine to cater for everyone, covering everything from the art to the hacking scenes. Unfortunately by dabbling into all these different areas means it is a master of none. ', 0, 'rev-03', NULL, NULL),
('Scene Charts', 'Santa', 'Scene.Charts', 'A gaming scene group review magazine created by Santa, the one time web master of the now defunct <a href="http://web.archive.org/web/19990430015915/http://www.scenereview.com/">www.scenereview.com</a>.', -1, 'scene_charts', NULL, NULL),
('Scooby Snack Magazine', NULL, 'Scooby.Snack.Magazine', 'This magazine was the first cracking magazine to be released for the Windows 95 operating system. Unfortunately the code in use feels very shaky and unstable. While there are some interesting features included, the magazine never managed to earn much respect and so it lost out on potential interviews and articles.\r\n\r\n<p><b>PLEASE NOTE ISSUE 1 MAYBE INFECTED WITH A \r\nBloodhound.AOLPWS VIRUS</b></p>', 0, 'ssm-2', NULL, '2008-12-12 06:38:32'),
('Software Chronicles Digest', NULL, 'Software.Chronicles.Digest', 'Software Chronicles Digest was one of the earliest coded magazines for the PC scene that started out in 1990. While coding wise the first issue was horrible, improvements where made over it''s two year lifetime. Software Chronicles Digest not only contains articles about pirates but also about the computer industry in general. Included as extras are a number of console and PC game reviews in various issues.', 0, 'scd-13', NULL, NULL),
('Some Weekly Chart', NULL, 'swc', 'Coming soon', -1, NULL, '2008-03-09 08:10:13', NULL),
('TFW', 'Q-Ball and CyberPhreak', 'Tfw.Game.Review', 'A RIP scene charting magazine from late 1996. Does anyone know that the T.F.W. stands for?', -1, NULL, NULL, NULL),
('The Bad News', 'Bad Ass Dudes', 'bad', 'From what can be read The Bad News came out every six months or so attempting to cover the news from within that period. Every issue would use a main topic that would be focused on extensively with the other unrelated news being relegated to the other areas of the magazine. The Bad News also covered basic phreaking, hacking and included some interviews.', 0, 'badnews9', NULL, '2007-07-14 08:15:02'),
('The Game Review', 'Ionizer', 'The.Game.Review', 'The Game Review was originally started as an additional section for The Week In Warez newsletter. At this time it wasn''t called ''The Game Review'' but rather ''Ionizer''s Game Review'', though the two did look very simular. Within a month of Ionizer''s Game Review initial publication The Week In Warez had stopped publishing. Ionizer found himself without a magazine to print his reviews in, so he simply started his own.<p></p>On the 5th of November 1995 the first ''The Game Review'' was released with the rejoicing of many people. By 1996 the newsletter found itself so popular that magazines such as Reality Check Network and Defacto included the newest editions as supplements in their own magazines. Some were even colourised. By the 4th of April 1997 though we saw the last issue of a continuous weekly review from Ionizer. He claimed he was going to return, and he did for a few more issues but unfortunately this never lasted.<p></p> <a href="http://tgr.ionin.net">The webpage can still be found online</a>.', -1, 'tgr', NULL, NULL),
('The Game Scene Chart', NULL, 'tgsc', 'The Game Scene Charts is an odd magazine inspired by not only the recent TNT Unbiased DOX Report but also chart magazines from long years past.<p>Unlike earlier scene publications TGSC doesn''t shy away from the various contributors of the scene. Counting every release from DOXs, to trainers to clones. Something that in the years past would have been totally frowned in the elite scene.</p><p>Issue 16 saw a slight name change and the introduction of a coded edition.</p>', 0, 'tgsc', '2006-12-18 05:11:51', '2008-02-11 05:55:42'),
('The Gamers Edge', NULL, 'Gamers.Edge', 'This game review magazine was founded in 1997 in a bid to compete with The Review Guild. Unlike The Review Guild though The Gamers Edge issues included a package of reviews aswell as gaming related articles such as hardware reviews. The Gamer''s Edge eventually merged with The Review Guild to form the now onetime famous www.game-over.net website.', 0, 'tge3', NULL, NULL),
('The Humble Review', 'The Humble Guys', 'Humble.Review', 'The first and only electronic magazine released by The Humble Guys FX division. It includes game reviews (with screen shots) and articles but no interviews. Well worth a look.', 0, 'humble-1', NULL, NULL),
('The Illustrator', 'iCE', 'theillust', 'Illustrator is an EGA ANSI with SoundBlaster support. The menu system while basic is quite usable but this it is more than made up by the huge number of articles contained within the magazine. These include a large collection of scene game reviews. 15 or so scene articles including a few rare scene interviews. A few pieces of literature and A huge collection of ANSI art from Tempus Thales of ICE as well as an additional art top 10.', 0, 'illus-1', '2007-07-14 01:17:00', '2007-08-01 07:34:48'),
('The Naked Truth Magazine', NULL, 'The.Naked.Truth.Magazine', 'The Naked Truth was a well respected magazine from 1995 which held it''s own against the likes of Inquisition. Unfortunatly the first issue never got off to a good start as it contained some very dated interviews. Things did pick up for Naked Truth Magazine, but with issues only being released on a monthly basis it never gained much of a foothold within the scene.', -1, 'ntm', NULL, NULL),
('The Net Monkey Weekly Report', NULL, 'NetMonkey.Weekend.Report', 'Founded in early 1998, Netmonkey Weekend Report as it originally was called (hence N.W.R) was formed as scoresheet for the courier scene and the top sites of the world. It''s founders thought the competition were not up to scratch and so they created their own report. This report quickly evolved into a regularly released text based magazine with thorough game and utility reviews, plus group and video reviews. And there is usually a couple of interviews or articles thrown in for good measure.<p></p>Net Monkey Weekly Report has been highly influenced by older text based magazines especially by Inquisition. This is not surprising seeing as one of the leaders of Inquisition is also became an editor of this magazine. It can be best described as a tabloid style text magazine that doesn''t take itself too seriously. While it does make a fun read and it can also be quite in depth and informative.', -1, 'nwr', NULL, NULL),
('The Pirate Syndicate', NULL, 'tps', 'The Pirate Syndicate is a generic EGA ANSI scene magazine from 1990. Included are your usual assortment of scene articles, ads, game reviews, hacking and area reviews. Stay clear of the first issue though as it has one of the worse user interfaces I have run into in recent times. The other issues are an improvement, but only slightly.', 0, 'tps-iss1', '2007-07-14 08:20:16', '2007-08-01 07:58:08'),
('The Product', 'Acid Productions', 'product', 'The Product was the first even major scene magazine by ACID, created back in 1992. While the interface is line ANSI, the magazine does supports common soundboards from the time as well as DOS mouse support! Contained within is a large collection of early ANSI related articles and art, back from when ANSI and pirating were still tied together.', 0, 'product', '2007-07-14 02:27:23', '2007-08-01 07:56:46'),
('The Unbiased DOX Report', 'The Nova Team', 'tnt', 'TNT''s Unbiased DOX report was the first scene new scene publication to come out for a number of years. Focusing exclusively on the DOX scene (cracks, trainers and documentation) rather then the more prestigious ISO or gaming scenes. This report has become more of a niche product. Though it report did inspire another scene group to take the concept further and create the more popular ''The Game Scene Chart''.', -1, 'DOX', '2007-04-15 08:22:53', '2007-04-15 09:06:20'),
('The Warez Report', 'The Renegade Chemist', 'The.Renegade.Chemist.Warez.Report', 'A detailed RIP scene group review and chart magazine by old time scener The Renegade Chemist. Eventually he gave up on the text magazine to instead start a web blog with simular content.', -1, NULL, NULL, NULL),
('The Week In Warez', NULL, 'The.Week.In.Warez', 'The Week In Warez is the predecessor to Inquisition which had it''s start in July 1995. The editors believed there was a need for a scene based newsletter to be released on a weekly basis. It was supported by some big name scene members including Lester, Bishop, Cyber Angel, Mikeysoft, Jimmy Jamez who all held prominent positions at the time.<p></p>\r\nThis magazine is definitely worth a look at as it established many conventions that all other future magazines would follow including the infamous Reality Check Network. If you check issue four of WWN you will discover Ionizer''s first Game Review article which would eventually lead him onto the path of the once famous The Game Review publication.', -1, 'wwn', NULL, NULL),
('Trip 2 Hell', NULL, 'Trip.2.Hell', 'Trip 2 Hell has more to do with the art scene then the pirate scene. Though it is included here because a \r\r\nnumber of interviews within the issues do have relevant scene information.', 0, 'trip0794', NULL, NULL),
('TSAN Newsletter', 'The SysOps Associated Network', 'tsann', 'The SysOps Associated Network was a network of USA based BBS that collectively shared resources including a message board system. In 1991 the group released this newsletter with the intention of it becoming regular.  Probably to not only to report on scene activities but to also promote the organisation, and its new message network TCSNet.', 0, 'tsan-1', '2007-07-14 08:36:00', '2007-08-01 08:09:03'),
('Unreal Magazine', NULL, 'Unreal.Magazine', 'The first two issues of Unreal are pretty unmemorable. Thankfully though by the third issue, released a year later the guys do a better job. Here is what they say <em>"UnReaL will try to focus on the ''underground'' computer art scene while providing a smattering of information on the underground scene as a whole."</em>', 0, 'unreal03', NULL, NULL),
('Wave', NULL, 'Wave', 'Released just after New Years in 1996 Wave was originally a coded magazine put out by the German group The Council. Eventually after issue five Wave went independent. Though that didn''t do anything to help their cause because simply put Wave just wasn''t all that good.<p></p>Wave was originally released on a monthly basis but eventually the time span  inbetween issues grew. Personly though I think the main reason why Wave was never too successful was simply that it was too quirky for most peoples tastes. After issue twelve Wave went from a DOS to Win32 code base before eventually dying after issue thirteen. The Win32 coding isn''t too bad I might add, though at times it does feel like you are reading a badly designed webpage rather then an electronic magazine.', 0, 'wave11', NULL, NULL),
('Worldcharts', 'Silents, Scoopex and Hoodlum', 'worldcharts', 'Worldcharts is a strange beast that has past through many developers on a variety of platforms. Originally created as a one off by the legendary Future Crew back in 1993. It strangely then found it''s subsequent releases on the Amiga under a different producer. Hoodlum eventually took over the release of the title after issue 10 before later sharing the work with Silents and Scoopex making it multiplatform.\r\n<p><a href="http://worldcharts.untergrund.net/">worldcharts.untergrund.net</a></p>', 0, NULL, '2007-07-14 08:40:38', '2007-08-12 19:47:38');
